### ISSUE TITLE
Smartbugs Wild Cleaned dataset.

### ISSUE THREAD

**Issue by minhnn32** [MANDO-Project/ge-sc-transformer#2]
Hi, I would like to know where can I find the smartbugs wild cleaned dataset with 2,742 contracts that do not have any bug.

**Comment by erichoang** [comment]
Hi @minhnn32 , I have just uploaded the 2742 clean contracts extracted from the SmartBugs Wild dataset. You can find it in the following link: 

[https://github.com/MANDO-Project/ge-sc-transformer/blob/main/experiments/ge-sc-data/source_code/smartbugs-wild-2742-clean-contracts.zip](https://github.com/MANDO-Project/ge-sc-transformer/blob/main/experiments/ge-sc-data/source_code/smartbugs-wild-2742-clean-contracts.zip)
